[package]
name = "gosub-engine-api"
version = "0.1.0"
edition = "2021"

[lib]
name = "gosub_engine"
crate-type = ["cdylib", "rlib"]

[[example]]
name = "gtk_cairo"
path = "examples/gtk_cairo/main.rs"
required-features = ["gtk4", "backend_cairo"]

[[example]]
name = "egui_vello"
path = "examples/egui_vello/main.rs"
required-features = ["ui_eframe", "backend_vello"]

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[dependencies]
uuid = {  version = "1.17.0", features = ["v4", "serde"] }
reqwest = { version = "0.12.22", features = ["json", "gzip", "brotli", "deflate", "cookies", "rustls-tls"] }
tokio = { version = "1.47", features = ["macros", "rt-multi-thread", "full", "tracing"] }
thiserror = "1.0.69"
rand = "0.9.2"
futures = { version = "0.3", features = ["executor"] }
anyhow = "1.0.98"
http = "1.3.1"
url = "2.5.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
log = "0.4.27"
lazy_static = "1.5.0"
pollster = { version = "0.4.0"}
env_logger = "0.11.8"

r2d2 = { version = "0.8", optional = true }
r2d2_sqlite = { version = "0.24", optional = true }

gtk4 = { version = "0.7", optional = true }
cairo-rs = { version = "0.21.1", optional = true }

skia-safe = { version = "0.87.0", optional = true }

vello = { version = "0.5.0", optional = true }
wgpu = { version = "24.0.5", optional = true }

winit = { version = "0.30.12", optional = true }


gdk4-wayland = { version = "0.8", optional = true, features = ["wayland_crate"] }
gdk4-x11     = { version = "0.8", optional = true }
raw-window-handle = "0.6"
gdk4 = "0.8.2"

eframe = { version = "0.31.0", optional = true, features = ["wgpu"] }
egui = { version = "0.31.0", optional = true }
png = "0.17.16"
futures-intrusive = "0.5.0"
parley = "0.5.0"
fontique = "0.5.0"
hashbrown = "0.15.5"
skrifa = "0.31.3"
num_cpus = "1.17.0"
time = "0.3.41"
tokio-util = "0.7.16"
tempfile = "3.21.0"
console-subscriber = "0.4.1"

[features]
default = ["sqlite_cookie_store", "parley_layout"]
ui_eframe = ["dep:eframe", "dep:egui"]
winit = ["dep:winit", "dep:wgpu"]
gtk4 = ["dep:gtk4", "dep:cairo-rs"]
sqlite_cookie_store = ["r2d2", "r2d2_sqlite"]
backend_cairo = ["dep:gtk4", "dep:cairo-rs"]
backend_vello = ["dep:vello", "dep:wgpu"]
backend_skia  = ["dep:skia-safe"]
parley_layout = []

wayland = ["gdk4-wayland"]
x11     = ["gdk4-x11"]
